# docker-compose.yml - Development environment
version: '3.8'

services:
  migration-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altium-kicad-migration
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    # Uncomment for GUI access (requires X11 forwarding)
    # environment:
    #   - DISPLAY=${DISPLAY}
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # network_mode: host
    
  # Optional: Database for testing
  test-database:
    image: postgres:13
    container_name: migration-test-db
    environment:
      - POSTGRES_DB=test_components
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: