name: Migrate Component Libraries

on:
  push:
    branches: [ main ]
    paths:
      - 'altium_libraries/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'altium_libraries/**'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unixodbc-dev
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Run migration
      run: |
        altium-kicad-migrate --input altium_libraries/main_library.DbLib \
                     --output kicad_libraries \
                     --library-name MainLibrary \
                     --parallel-processing \
                     --max-workers 4 \
                     --generate-report
    
    - name: Upload KiCAD libraries
      uses: actions/upload-artifact@v3
      with:
        name: kicad-libraries
        path: kicad_libraries/
    
    - name: Upload migration report
      uses: actions/upload-artifact@v3
      with:
        name: migration-report
        path: migration_report.html

  test_libraries:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - uses: actions/checkout@v4
      
      - name: Download KiCAD libraries
        uses: actions/download-artifact@v3
        with:
          name: kicad-libraries
          path: kicad_libraries/
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Run library validation tests
        run: pytest tests/test_library_validation.py -v

  publish_libraries:
    runs-on: ubuntu-latest
    needs: test_libraries
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download KiCAD libraries
        uses: actions/download-artifact@v3
        with:
          name: kicad-libraries
          path: kicad_libraries/
      
      - name: Set up Git
        run: |
          git config --global user.name "Library Bot"
          git config --global user.email "bot@example.com"
      
      - name: Commit and push libraries
        run: |
          git add kicad_libraries/
          if ! git diff --staged --quiet; then
            git commit -m "Update KiCAD libraries [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
      
      - name: Create release
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: library-v${{ github.run_number }}
          release_name: Library Update v${{ github.run_number }}
          body: |
            Automated library update from Altium sources.
            
            See migration report for details.
          draft: false
          prerelease: false
        continue-on-error: true